declare namespace NodeJS {
  export interface ProcessEnv {
    NEXTAUTH_URL: string;
    NEXTAUTH_SECRET: string;
    CONNECTOR_GITHUB_CLIENT_ID: string;
    CONNECTOR_GITHUB_CLIENT_SECRET: string;
    CONNECTOR_FACEBOOK_CLIENT_ID: string;
    CONNECTOR_FACEBOOK_CLIENT_SECRET: string;
    CONNECTOR_TWITTER_CLIENT_ID: string;
    CONNECTOR_TWITTER_CLIENT_SECRET: string;
    CONNECTOR_GOOGLE_CLIENT_ID: string;
    CONNECTOR_GOOGLE_CLIENT_SECRET: string;
    CONNECTOR_AUTH0_CLIENT_ID: string;
    CONNECTOR_AUTH0_CLIENT_SECRET: string;
  }
}
